# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 3, 14, 38, 734101, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
