# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_items', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
