# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_items', '0005_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='deadline',
            field=models.DateField(),
        ),
    ]
