# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_items', '0007_auto_20160414_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='item_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
