# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_items', '0009_pledge_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitem',
            name='image_url',
            field=models.URLField(default='NA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishitem',
            name='item_link',
            field=models.URLField(default='NA'),
            preserve_default=False,
        ),
    ]
